language: ruby
cache: bundler
global:
  - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
services:
  - postgresql
  - redis-server
sudo: false
install:
  - bundle install --jobs 4 --retry 4
before_script:
  - cp .env.sample .env
  - bundle exec rake db:create db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - bundle exec rspec spec
deploy:
  provider: heroku
  app: dear-future-me
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  run:
    - bundle exec rake db:migrate
