language: ruby
cache: bundler
services:
  - postgresql
  - redis-server
sudo: false
install:
  - bundle install --jobs 4 --retry 4
before_script:
  - cp .env.sample .env
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec spec
deploy:
  provider: heroku
  app: dear-future-me
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  run:
    - bundle exec rake db:migrate
