default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dear_me_development
  #username: dear_me
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: dear_me_test

production:
  <<: *default
  database: dear_me_production
  username: dear_me
  password: <%= ENV['DEAR_ME_DATABASE_PASSWORD'] %>
